module.exports = [
  'Astralópolis', 'Arcanópolis', 'Aventúria', 'Arco Celeste', 'Alta Vista', 'Água Clara', 'Andorinha', 'Alegria', 'Aurora', 'Amizápolis',
  'Brancaflor', 'Bosque Encantado', 'Brisa Mar', 'Céu Estrelado', 'Cidade das Maravilhas', 'Canto dos Sonhos', 'Cascata Mágica', 'Cidade Radiante', 'Cidade dos Ventos', 'Coração Azul',
  'Diamante Celestial', 'Dunas Douradas', 'Doce Lar', 'Dália Dourada', 'Desejo Estelar', 'Diamante do Norte', 'Dolce Vita', 'Destino dos Sonhos', 'Duna Dourada', 'Doces Ventos',
  'Esperança Eterna', 'Estrela Guia', 'Eco Ville', 'Eldorado', 'Epicidade', 'Encanto Celestial', 'Estrela do Norte', 'Esplendor Azul', 'Eterna Primavera', 'Encantópolis',
  'Fantasia Feliz', 'Floresta Encantada', 'Florada Luminosa', 'Felicidade Radiante', 'Flores do Amanhã', 'Flor do Luar', 'Felicidade Eterna', 'Fascínio das Estrelas', 'Fonte dos Desejos', 'Fênix Dourada',
  'Galáxia dos Sonhos', 'Girassol Dourado', 'Grande Aurora', 'Gardenópolis', 'Gloriosa Cidade', 'Galáxia Encantada', 'Gazeta dos Sonhos', 'Grande Imaginação', 'Grande Sonho', 'Gosto Bom',
  'Harmonia Celestial', 'Horizonte Encantado', 'Holofotes Mágicos', 'Harmonia dos Ventos', 'Heavenly Haven', 'Horizonte Infinito', 'História Mágica', 'Haven Hill', 'Harpa Celestial', 'Horizonte Dourado',
  'Ilusão Incrível', 'Imaginação Infinda', 'Inspiração do Luar', 'Infinidade Celestial', 'Ilha das Maravilhas', 'Incrível Aurora', 'Illuminação Eterna', 'Icônica Imaginação', 'Ilha do Luar', 'Inspiração Cintilante',
  'Jardim do Sol', 'Jovialidade Jovial', 'Jurassic Joy', 'Jardim das Estrelas', 'Jazz Jamboree', 'Júbilo da Juventude', 'Júbilo Jovial', 'Jardim das Jóias', 'Janela do Jasmim', 'Jovialidade Jubilante',
  'Kaleidoscópio Kintético', 'Kaleidoscópio Kintilar', 'Kaleidoscópio Karmesim', 'Kaleidoscópio Kriativo', 'Kaleidoscópio Kintilante', 'Kaleidoscópio Kintilhar', 'Kaleidoscópio Kintilux', 'Kaleidoscópio Kriativo', 'Kaleidoscópio Kintilante', 'Kaleidoscópio Kintilhar',
  'Luar Luminoso', 'Lagoa Luminosa', 'Luz do Amanhecer', 'Liberdade Luminosa', 'Lar Luminar', 'Luz Leve', 'Luz Lunar', 'Lucent Lagoon', 'Luar Lilás', 'Luz do Levante',
  'Montanha Mágica', 'Mundo Místico', 'Miragem Mágica', 'Maravilha do Norte', 'Mundo Mágico', 'Mágico Marítimo', 'Melodia Mística', 'Morada Mágica', 'Mundo Místico', 'Mirante Mágico',
  'Noite Nova', 'Nascente do Sol', 'Nuvem Nove', 'Nebulosa Noturna', 'Nova Névoa', 'Nuvem Nevada', 'Núcleo da Noite', 'Ninho do Norte', 'Névoa Noturna', 'Nascente Nebulosa',
  'Oásis Ofuscante', 'Ouro Ondulante', 'Oceano Ônix', 'Oscilação Opulenta', 'Odisseia do Oeste', 'Olimpo Onírico', 'Olivais Ônix', 'Opulência Oculta', 'Orquídea Ofuscante', 'Orvalho Opulento',
  'Paisagem Poética', 'Paraíso Pintado', 'Pico Pintoresco', 'Palácio Prismático', 'Praia Paradisíaca', 'Ponte do Poente', 'Pico Ponderoso', 'Paisagem Primordial', 'Praça Pitoresca', 'Paraíso Púrpura',
  'Quintal Querido', 'Quintal Quântico', 'Queensland Querida', 'Quintal Querência', 'Quarteto Querido', 'Quebra-Cabeça Quântico', 'Quadrante Quântico', 'Querência Querida', 'Quimera Quântica', 'Queensland Quântico',
  'Rosa Radiante', 'Roda do Relâmpago', 'Rubi Radiante', 'Reino Reluzente', 'Raio da Riqueza', 'Recanto Rubro', 'Ramo Rubi', 'Resplendor Rubro', 'Recreio Risonho', 'Rosa Rústica',
  'Sol Sutil', 'Sinfonia Serena', 'Solaris Suave', 'Sonho Selvagem', 'Sintonia Suave', 'Sorriso Sincero', 'Safira Serena', 'Suíte Solar', 'Saudade Sutil', 'Sabor Sutil',
  'Terra Tranquila', 'Terra Tumultuada', 'Tranquilidade Tropical', 'Terra Trançada', 'Travessia Tranquila', 'Turquesa Tranquila', 'Tranquilidade Tintada', 'Tapeçaria Tropical', 'Terracota Tranquila', 'Tremor Tropical',
  'Unicórnio Urbano', 'Universo Urbano', 'Utopia Urbana', 'Urbano Único', 'Urbano Ultrajante', 'Universo Unido', 'Urbano Último', 'Utopia Única', 'Urbano Último', 'Ultrassom Urbano',
  'Vila Viva', 'Vila Verde', 'Vila Valente', 'Vila Veloz', 'Vila Vinhedo', 'Vale Verde', 'Vila Venturosa', 'Vista Vermelha', 'Vila Vibrante', 'Vila Vinícola',
  'Whisky Wonderland', 'Westminster Wonders', 'Webster\'s Way', 'Wondrous Wellington', 'Wandering Wits', 'Wisteria Whirl', 'Wanderlust Wonders', 'Wistful Whisper', 'Witty Wonderland', 'Wisp of Wonder',
  'Xanadu Xenial', 'Xenon X-factor', 'Xylophone Xanadu', 'X-factor Xenial', 'Xanadu X-factor', 'Xerox X-factor', 'Xanadu Xenon', 'Xylophone Xenial', 'X-factor Xenon', 'Xanadu Xylophone',
  'Yara Yonder', 'Yosemite Yarn', 'Yonder Yarn', 'Yoga Yonder', 'Yuletide Yarn', 'Yonder Yarn', 'Yoga Yonder', 'Yoga York', 'Yosemite Yarn', 'Yonder Yule',
  'Zephyr Zenith', 'Zenithal Zephyr', 'Zestful Zenith', 'Zebra Zest', 'Zenith Zephyr', 'Zephyr Zest', 'Zircon Zenith', 'Zestful Zephyr', 'Zephyr Zest', 'Zircon Zest',
];