module.exports = [
  'Astralândia', 'Aventúria', 'Açucarlândia', 'Amazônia', 'Alvorada',
  'Brisalândia', 'Braveville', 'Belfort', 'Bosque Verde', 'Brancaflor',
  'Cidadela', 'Céu Azul', 'Coralândia', 'Caminho do Sol', 'Cidadão',
  'Diamantina', 'Dourados', 'Dolce Vista', 'Divina', 'Dália Dourada',
  'Esplendor', 'Epicidade', 'Eco Vila', 'Estrelar', 'Encantópolis',
  'Fantásia', 'Florestalândia', 'Florada', 'Felicidade', 'Fênix',
  'Galáxia', 'Girassol', 'Gardenópolis', 'Gazeta Verde', 'Glamour',
  'Harmonia', 'Horizontina', 'Holambra', 'Haven', 'Harpa',
  'Ilusão', 'Inspiração', 'Imperialândia', 'Ilha do Sol', 'Infinity',
  'Jovialidade', 'Jurassic', 'Jardim das Jóias', 'Júbilo', 'Jasmine',
  'Kaleidoscópio', 'Kamaiurá', 'Karaguatá', 'Kintético', 'Kriativo',
  'Luz do Luar', 'Liberdade', 'Lagoa Lunar', 'Luminalândia', 'Luar Lilás',
  'Mágico', 'Maravilha', 'Montanha', 'Miragem', 'Místico',
  'Nuvem Nova', 'Nascente', 'Névoa Noturna', 'Ninho', 'Náutica',
  'Oásis', 'Ouro Ondulante', 'Olimpo', 'Opulência', 'Orquídea',
  'Paraíso', 'Pico Ponderoso', 'Palácio', 'Pitoresca', 'Primordial',
  'Quintal', 'Queensland', 'Quadrante', 'Querência', 'Quinteto',
  'Rubi Radiante', 'Raio Risonho', 'Recanto', 'Rusticana', 'Resplendor',
  'Solar', 'Sintonia', 'Sinfonia', 'Sonho', 'Sorriso',
  'Terra Tropical', 'Tranquilidade', 'Turquesa', 'Tremor', 'Terracota',
  'Universo', 'Urbano', 'Utopia', 'Ultrajante', 'Último',
  'Vila Verde', 'Vale Vermelho', 'Vibrante', 'Vinícola', 'Valente',
  'Wonderland', 'Wondrous', 'Wandering', 'Witty', 'Whisky',
  'Xanadu', 'Xenon', 'X-factor', 'Xylophone', 'Xerém',
  'Yoga', 'Yara', 'Yankee', 'Yasmin', 'Yokohama',
  'Zélandia', 'Zafira', 'Zamboni', 'Zum-Zum', 'Zephyr',
];