module.exports = [
  'Alameda', 'Avenida', 'Azul', 'Amendoeira', 'Alegria', 'Amor', 'Aroeira', 'Aurora', 'América', 'Acacio', 'Alvorada', 'Acai', 'Aconchego', 'Agricola', 'Anjo',
  'Bela Vista', 'Bandeirantes', 'Brisa', 'Bromelias', 'Bambu', 'Beira-Rio', 'Boulevard', 'Barao', 'Bosque', 'Bem-Te-Vi', 'Barroso', 'Branca', 'Branco', 'Brisa Mar', 'Bambuzal',
  'Caminho do Sol', 'Castelo', 'Cerejeira', 'Cidade Nova', 'Cipreste', 'Cascata', 'Canto do Sabia', 'Corais', 'Colina', 'Curva do Rio', 'Copaiba', 'Carvalho', 'Ceu Azul', 'Chacara', 'Ciranda',
  'Diamante', 'Dunas', 'Dalia', 'Divisa', 'Doce Lar', 'Delfim', 'Desembargador', 'Domingos', 'Danubio', 'Dalia', 'Dunas', 'Doutor', 'Diogenes', 'Dolores', 'Dez de Julho',
  'Esperanca', 'Eucalipto', 'Estrela', 'Entre Rios', 'Elegancia', 'Encanto', 'Estacao', 'Estrada Real', 'Emilio', 'Esmalte', 'Ernesto', 'Eucaliptos', 'Europa', 'Esplanada', 'Eco',
  'Felicidade', 'Figueira', 'Flamingo', 'Fazenda', 'Flores', 'Flamboyant', 'Fagundes', 'Francisco', 'Fogao', 'Fiori', 'Fazendinha', 'Fidalgo', 'Fidalga', 'Feijo', 'Foz do Iguacu',
  'Girassol', 'Gardenia', 'Goiaba', 'Gaviao', 'Glicinia', 'Girafa', 'Garibaldi', 'Gosto Bom', 'Granada', 'Grafite', 'Gramado', 'Gancho', 'Gloriosa', 'Guilherme', 'Goleiro',
  'Hortensia', 'Horizonte', 'Humaita', 'Hugo', 'Harmonia', 'Holanda', 'Hollywood', 'Havai', 'Heitor', 'Horto', 'Helena', 'Hipotenusa', 'Havaiano', 'Heroi', 'Heranca',
  'Iris', 'Ilha Bela', 'Ipanema', 'Imperial', 'Italia', 'Independencia', 'Iguana', 'Iluminado', 'Inacio', 'Ibis', 'Isaias', 'Ivoti', 'Iguatu', 'Ilusao', 'Ideal',
  'Jasmim', 'Joao Pessoa', 'Jardim', 'Jardins', 'Jaqueira', 'Jasmim', 'Juriti', 'Javari', 'Joaquim', 'Jerusalem', 'Jandaia', 'Jambo', 'Jabuticaba', 'Jaburu', 'Jasmim do Campo',
  'Kaleidoscopio', 'Kaiak', 'Karate', 'Kosmos', 'Kanagawa', 'Kopenhagen', 'Kamikaze', 'Kiwi', 'Kombi', 'Kung Fu', 'Kefir', 'Karate', 'Koala', 'Kelp', 'Kaleidoscopico',
  'Lagoa Azul', 'Luz do Sol', 'Liberdade', 'Lua Cheia', 'Laranjeiras', 'Luminosa', 'Leblon', 'Lavanda', 'Lirio', 'Lider', 'Laguna', 'Largo', 'Lautert', 'Leao', 'Leste',
  'Magnolia', 'Mandacaru', 'Margarida', 'Maravilha', 'Monte Verde', 'Mangueira', 'Matriz', 'Miragem', 'Minuano', 'Martir', 'Moinho', 'Miosotis', 'Matinal', 'Macuco', 'Mae d\'Agua',
  'Nogueira', 'Nautico', 'Nuvem Branca', 'Narciso', 'Novo Horizonte', 'Ninho Verde', 'Nazare', 'Nativo', 'Neblina', 'Nova Esperanca', 'Niquel', 'Nacar', 'Ninho das Aguias', 'Nevado', 'Naufrago',
  'Oasis', 'Oliveira', 'Orquidea', 'Ouro Preto', 'Oriento', 'Oceano', 'Oiticica', 'Obelisco', 'Oliveira', 'Olinda', 'Oscar', 'Ocre', 'Ouro Fino', 'Olaria', 'Orla Maritima',
  'Praia Grande', 'Perola', 'Pampulha', 'Ponte Alta', 'Palmeiras', 'Paraiso', 'Pinheiro', 'Primavera', 'Paz', 'Pescador', 'Por do Sol', 'Porto Seguro', 'Pingo d\'Agua', 'Panda', 'Pulmao',
  'Quaresmeira', 'Quinta Avenida', 'Quilombo', 'Quedas d\'Agua', 'Quintal', 'Quixote', 'Quasar', 'Quilometro', 'Quando', 'Quartzo', 'Quintana', 'Quebramar', 'Quadra', 'Queijadinha', 'Quindim',
  'Rua Nova', 'Raizes', 'Ribeirao', 'Rosa Negra', 'Rio Branco', 'Rancho Fundo', 'Raios de Sol', 'Recanto Feliz', 'Romeu', 'Rainha', 'Rancho Alegre', 'Roda Mundo', 'Rosa dos Ventos', 'Recanto do Sol', 'Romeu e Julieta',
  'Sol Nascente', 'Serra Azul', 'Sonho Meu', 'Santo Antonio', 'Serenata', 'Sambaqui', 'Salto Alto', 'Sonho Bom', 'Sinfonia', 'Solaris', 'Saudade', 'Semente', 'Sorriso', 'Sertao', 'Simplicidade',
  'Terra Nova', 'Travessa das Flores', 'Tango', 'Ternura', 'Tiara', 'Trovador', 'Terra do Sol', 'Trevo', 'Triunfo', 'Tijuca', 'Toque Magico', 'Tamandua', 'Topazio', 'Ternura', 'Travessa do Bosque',
  'Uniao', 'Urano', 'Utopia', 'Uirapuru', 'Unicornio', 'Umbuzeiro', 'Universo', 'Umbral', 'Uva', 'Urso Polar', 'Umbanda', 'Uma So', 'Unissono', 'Ultrapassagem', 'Usina',
  'Veneza', 'Vila Bela', 'Via Lactea', 'Veneza', 'Vitoria Regia', 'Voo Livre', 'Vida Nova', 'Vermelho', 'Ventos Alisios', 'Villa Lobos', 'Vitoria', 'Vila das Oliveiras', 'Verde Mar', 'Vila dos Passaros', 'Vale Verde',
  'Whisky', 'Westminster', 'Webster', 'Wellington', 'Wagner', 'William', 'Walmart', 'Wisconsin', 'Wimbledon', 'Washington', 'Walter', 'Windsor', 'West', 'Wanderlust', 'Waterloo',
  'Xangri-la', 'Xisto', 'Xerife', 'Xerem', 'Xango', 'Xara', 'Xale', 'Xavante', 'Xote', 'Xingu', 'Xanadu', 'Xerem', 'Xote Gaucho', 'Xale de Seda', 'Xicara',
  'Yara', 'Yoga', 'Yasmin', 'Ypiranga', 'Yorkshire', 'Yankee', 'Yogurte', 'Yucca', 'Yale', 'Yin-Yang', 'Youtuber', 'Yucca', 'Yogini', 'Yacht', 'Yara do Mar', 'Yoga na Praia',
  'Zingaro', 'Zafira', 'Zenite', 'Zodiaco', 'Zombaria', 'Zelador', 'Zarolho', 'Zigue-Zague', 'Zodiaco', 'Zenite', 'Zebra', 'Zefir', 'Zorrilho', 'Zarpar', 'Zunzum', 'Zangaia'
];